### ISSUE TITLE
Calibration of the expression pedal range

### ISSUE THREAD

**Issue by haggl** [theFork/uMIDI#34]
Calibration of the ADC at startup is annoying. It is also not enough, as the sent MIDI values never exceed 103.

We have to implement some kind of seamless auto-calibration or a way of manually triggering a device calibration procedure and storage of correction values.

**Comment by theFork** [comment]
IMHO calibration should be initiated via USB serial console

**Comment by haggl** [comment]
Fixed: 36b27bf
