### ISSUE TITLE
Add firmware version info to VCP help string

### ISSUE THREAD

**Issue by theFork** [theFork/uMIDI#48]
When entering help into the serial console, it should say something like
`<src/switcher> Build 2015-08-15 git 5b88bde`
I'm afraid that a tough one... But really helpful!

**Comment by haggl** [comment]
Hmm I agree, that would be quite helpful. I'll think about it..

**Comment by haggl** [comment]
May be not that hard after all:

We could create little script in the toolchain that does the following:
1. Use `git describe --all --dirty --always` to extract SCM information. This generates a string of the form `heads/app/switcher-dirty`.
2. Format the string (remove "heads/", add current date).
3. Generate a C header file containing the resulting string in a `#define`.
This macro could then be used in a `usb_printf()`-statement.

It is also possible to to all this directly in a make recipe.

**Comment by haggl** [comment]
19d81ea :+1:
