### ISSUE TITLE
Hand NoteOn velocity over to handler

### ISSUE THREAD

**Issue by theFork** [theFork/uMIDI#54]
Currently the NoteOn callbacks only get the note value and no velocity. Some devices (Behringer FCB1010) apparently prefer to use NoteOn with velocity=0 over sending NoteOff commands.

For the switcher toggle output feature it is required to get to know the velocity.

**Comment by haggl** [comment]
See corresponding branch. Please rebase your branch and test if it works.

**Comment by theFork** [comment]
Works. Feature used in switcher app (36d6428).
