### ISSUE TITLE
First few firmware bytes vanish randomly

### ISSUE THREAD

**Issue by haggl** [theFork/uMIDI#55]
See: https://github.com/theFork/uMIDI-switcher/issues/1

The bug can be avoided by erasing the chip and *not* installing the bootloader.

To reproduce the bug, install the bootloader and clean app/switcher build (48c2843).

**Comment by haggl** [comment]
Activating the brown-out detection seems to fix it.

**Comment by theFork** [comment]
Yes! It did not happen again.

Activating brown-out detection apparently also fixes startup issues with the expression pedal.
