### ISSUE TITLE
SPI master module

### ISSUE THREAD

**Issue by theFork** [theFork/uMIDI#59]
- Implement a generic bit-bang SPI master module

## Properties
- Pinout
  - miso_pin: gpio_pin (may be NULL if not present)
  - mosi_pin: gpio_pin (may be NULL if not present)
  - clk_pin: gpio_pin
- Further properties:
  - word_length: int
  - clk_pol: bool
  - clk_pha: bool

## API functions
- init
- transceive (send and receive a word at once)
- select (de/assert chip select)

**Comment by haggl** [comment]
Merged: 974d2a9
